/* eslint-disable */
export const people = [
  {
    id: '01',
    img: 'assets/images/team/undram.jpeg',
    name: 'Undram Lkhagvasuren',
    role: 'Managing Partner',
    about: 'Undram practices in the areas of Corporate, Commercial, Real Estate and Energy and Resources Law and has advised on a wide range of commercial transactions including takeovers, mergers, acquisitions, disposals, capital raising, joint ventures and mining operational agreements. She has conducted comprehensive compliance and due diligence programs in those areas. She as considerable experience in capital market having advised on several Mongolian Stock Exchange listings and IPOs. She also advised Shangri-La International Hotel Management for its local subsidiaries together with team, s China (establishment of the Representative Office in Mongolia and advised in numerous financing transaction), and US Government in acquisition of new mission premises in Ulaanbaatar Mongolia, Golomt Capital Securities, a leading securities brokerage, and underwriter company in Mongolia',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '02',
    img: 'assets/images/team/bayarjargal.jpeg',
    name: 'Bayarjargal Sodbaatar',
    role: 'Partner',
    about: 'Bayarjargal Sodbaatar specialises in general corporate transactions, M&amp;A, commercial bank lending, project finance, real estate with a particular focus on international commercial transactions. She has extensive experience representing various international financial institutions on financial transactions originating in Mongolia, Asia and Europe. Her experience also includes advising on regulatory matters relating to large scale infrastructure projects as well as various investment arrangements.',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '03',
    img: 'assets/images/team/maralgoo.jpeg',
    name: 'Maralgoo Dashdoorov',
    role: 'Counsel',
    about: 'Maralgoo advises businesspersons and companies on business, commercial, corporate and dispute resolution matters. She has extensive experience in advising in company establishment, commercial contracts and corporate issues.',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '04',
    img: 'assets/images/team/team-01.jpg',
    name: 'Munkhjargal Galsanjamts',
    role: 'Counsel',
    about: 'Counsel',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '05',
    img: 'assets/images/team/aldar.jpeg',
    name: 'Vyacheslav Kekeshkeev',
    role: 'Foreign Associate',
    about: 'Graduated from the Higher School of Economics in Moscow in 2021. Practical experience in civil, contract and labour law. Worked at the Skolkovo Innovation Center, the Labour Inspectorate in the Republic of Kalmykia.',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '06',
    img: 'assets/images/team/team-01.jpg',
    name: 'Gantushig Erdenebat',
    role: 'Junior Associate',
    about: 'Junior Associate',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '07',
    img: 'assets/images/team/team-01.jpg',
    name: 'Uugandari Tsogt',
    role: 'Counsel',
    about: 'Counsel',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '08',
    img: 'assets/images/team/team-01.jpg',
    name: 'Bulgankhangai Bayasgalan',
    role: 'Admin Manager',
    about: 'Admin Manager',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
];
