/* eslint-disable */
export const people = [
  {
    id: '01',
    img: 'assets/images/team/undram1.png',
    name: 'Undram Lkhagvasuren',
    role: 'Managing Partner',
    about: "Undram specializes in Corporate, Commercial, Real Estate, and Energy and Resources Law, offering expert counsel on a diverse spectrum of commercial transactions. Her advisory portfolio spans takeovers, mergers, acquisitions, disposals, capital raising, joint ventures, and mining operational agreements. She possesses extensive expertise in the capital and finance markets, providing strategic guidance on multiple Mongolian Stock Exchange listings and initial public offerings (IPOs). <br><br> Her professional repertoire includes the implementation of thorough compliance and due diligence programs within these domains. Notably, Undram has played a pivotal role in advising Shangri-La International Hotel Management on matters concerning its local subsidiaries, collaborating closely with the team. She also contributed to facilitating the establishment of the Bank of China's Representative Office in Mongolia, offering valuable insights into numerous financing transactions. Additionally, she provided advisory services to the US Government in the acquisition of new mission premises in Ulaanbaatar, Mongolia. <br> <br>Undram consistently serves as a trusted advisor to Golomt Capital Securities, a preeminent securities brokerage and underwriting company in Mongolia. Her commitment to excellence and wealth of experience underscore her standing as a distinguished professional in the legal and financial arenas.",
    phone: '+(976) 75350835',
    email: 'undram@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '02',
    img: 'assets/images/team/bayarjargal1.jpeg',
    name: 'Bayarjargal Sodbaatar',
    role: 'Partner',
    about: "Bayarjargal Sodbaatar specializes in general corporate transactions, mergers and acquisitions (M&A), commercial bank lending, project finance, and real estate, with a particular emphasis on international commercial transactions. Her expertise encompasses a wide range of legal facets, and she brings substantial experience to each facet of her practice.  <br><br>With a notable focus on international commercial transactions, Bayarjargal has demonstrated proficiency in navigating the complexities of such engagements. She has successfully managed various corporate transactions, including M&A deals, and has played a key role in commercial bank lending and project finance matters. Her keen understanding of real estate law further enhances her ability to provide comprehensive legal support across diverse sectors. <br><br>Bayarjargal's professional portfolio extends to representing numerous international financial institutions in complex financial transactions originating in Mongolia, Asia, and Europe. Her adept handling of these transactions reflects her nuanced understanding of the legal intricacies involved in cross-border dealings. <br><br>Furthermore, Bayarjargal's practice includes advising on regulatory matters pertaining to large-scale infrastructure projects. She brings a wealth of knowledge to navigating the legal landscape associated with major development initiatives. Additionally, her expertise encompasses providing legal counsel on various investment arrangements, showcasing her versatility in addressing the multifaceted aspects of business and finance law. <br><br>In summary, Bayarjargal Sodbaatar is a seasoned legal professional with a comprehensive skill set, particularly in the realm of international commercial transactions, corporate law, and financial matters. Her extensive experience and adept navigation of legal complexities make her a valuable asset in representing clients across diverse sectors and jurisdictions.",
    phone: '+(976) 75350835',
    email: 'bayarjargal@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '03',
    img: 'assets/images/team/maralgoo1.jpeg',
    name: 'Maralgoo Dashdoorov',
    role: 'Counsel',
    about: 'Maralgoo advises businesspersons and companies on business, commercial, corporate and dispute resolution matters. She has extensive experience in advising in company establishment, commercial contracts and corporate issues.',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '04',
    img: 'assets/images/team/team-01.jpg',
    name: 'Munkhjargal Galsanjamts',
    role: 'Counsel',
    about: "Munkhjargal provides expert counsel to businesspersons and companies, specializing in a broad spectrum of legal areas, including business law, commercial law, corporate law, and dispute resolution. Her wealth of experience encompasses various facets of business operations, making her a trusted advisor for clients seeking comprehensive legal guidance. <br><br>One of Munkhjargal's key areas of expertise lies in advising on company establishment. Her proficiency in this area involves navigating the intricacies of legal frameworks to ensure the smooth and compliant establishment of companies. This includes providing strategic guidance on regulatory compliance, structuring, and governance matters to facilitate the successful initiation of business entities. <br><br>In the realm of commercial contracts, Munkjargal brings a keen eye for detail and a thorough understanding of contractual nuances. She offers valuable insights to clients engaged in diverse commercial transactions, ensuring that contracts are meticulously drafted and negotiated to safeguard their interests. Her approach is characterized by a focus on clarity, risk mitigation, and the creation of mutually beneficial contractual relationships. <br><br>Munkhjargal's corporate advisory services extend beyond establishment and contract matters. She is well-versed in addressing a wide array of corporate issues, providing strategic solutions to challenges that businesses may encounter. Whether it involves compliance with corporate regulations, governance issues, or other corporate complexities, Munkhjargal is equipped to offer sound legal advice tailored to the unique needs of her clients. <br><br>Additionally, Munkhjargal is skilled in dispute resolution, offering her expertise to navigate legal conflicts that may arise in the course of business activities. Her approach to dispute resolution involves a combination of negotiation, mediation, and, when necessary, legal proceedings, with the goal of achieving optimal outcomes for her clients.",
    phone: '+(976) 75350835',
    email: 'munkhjargal@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '05',
    img: 'assets/images/team/aldar1.jpeg',
    name: 'Vyacheslav Kekeshkeev',
    role: 'Foreign Associate',
    about: "Vyacheslav Kekeshkeev is a graduate of the Higher School of Economics in Moscow, having completed his studies in 2021. His educational background is grounded in a comprehensive understanding of legal principles, particularly in the realms of civil, contract, and labor law. <br><br> Vyacheslav has translated his academic knowledge into practical expertise through his professional experiences. His tenure at the Skolkovo Innovation Center provided him with valuable insights into the legal intricacies of the innovation and entrepreneurship landscape. During this time, he engaged with legal matters pertaining to intellectual property, business contracts, and regulatory compliance, contributing to the legal framework supporting innovation initiatives. <br><br>In addition to his work at the Skolkovo Innovation Center, Vyacheslav has also been actively involved with the Labour Inspectorate in the Republic of Kalmykia. This experience has equipped him with practical insights into labor law matters, where he dealt with issues related to employment contracts, workplace regulations, and the resolution of labor disputes. His contributions to ensuring compliance with labor laws underscore his commitment to fostering fair and lawful employment practices.",
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '07',
    img: 'assets/images/team/uugandari1.png',
    name: 'Uugandari Tsogt',
    role: 'Counsel',
    about: 'Counsel',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
  {
    id: '08',
    img: 'assets/images/team/team-01.jpg',
    name: 'Bulgankhangai Bayasgalan',
    role: 'Admin Manager',
    about: 'Admin Manager',
    phone: '+(976) 75350835',
    email: 'contact@cosanex.mn',
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
  },
];
